### ISSUE TITLE
Should @docker:CopyFiles copy the files to the created docker/ directory? 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/module-ballerina-docker#294]
**Description:**
$title?

Currently, whatever the files specified in the annotation seem to be copied to the docker directory created.

```cmd
$ tree
.
├── abc.bal
├── abc.jar
├── docker
│   ├── Dockerfile
│   ├── foo.txt
│   └── qwe.conf
├── foo.txt
└── qwe.conf

1 directory, 7 files
```

Is this intended?

**Comment by anuruddhal** [comment]
Yes. This is done in order to minimize the size of the Docker build context.  Only the required files to build the docker image are copied to this directory and build is performed against it. Otherwise, there will be a performance impact. 

However, we can delete the files after creating the docker image. But users will have to copy all the artifacts back if they were to rebuild the image manually.  

Maybe we can introduce a new attribute like `@docker:Config{ cleanUp:true }` and handle the deletion.

**Comment by anupama-pathirage** [comment]
Closing as the question is answered.
